name: INA-DBNet_py38
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2025.9.9=h06a4308_0
  - cffi=1.17.1=py38h1fdaa30_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.3.0=py38h54f3939_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.5=h7934f7d_0
  - ninja=1.12.1=h06a4308_0
  - ninja-base=1.12.1=hdb19cb5_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=24.2=py38h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pycparser=2.21=pyhd3eb1b0_0
  - python=3.8.20=he870216_0
  - readline=8.3=hc2a1206_0
  - setuptools=75.1.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - unzip=6.0=h611a1e1_0
  - wheel=0.44.0=py38h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - anyconfig==0.14.0
      - blinker==1.8.2
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.1.8
      - contourpy==1.1.1
      - cycler==0.12.1
      - editdistance==0.8.1
      - filelock==3.16.1
      - flask==3.0.3
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - gevent==24.2.1
      - gevent-websocket==0.10.1
      - greenlet==3.1.1
      - hf-xet==1.1.10
      - huggingface-hub==0.35.3
      - idna==3.10
      - imageio==2.35.1
      - imgaug==0.2.8
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mpmath==1.3.0
      - munch==4.0.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.1.2.30
      - packaging==25.0
      - pillow==10.4.0
      - protobuf==5.29.5
      - pyclipper==1.3.0.post6
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pywavelets==1.4.1
      - pyyaml==6.0.3
      - requests==2.32.4
      - scikit-image==0.21.0
      - scipy==1.10.1
      - shapely==2.0.7
      - sortedcontainers==2.4.0
      - sympy==1.13.3
      - tensorboardx==2.6.2.2
      - tifffile==2023.7.10
      - timm==0.6.11
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.67.1
      - triton==3.0.0
      - typing-extensions==4.13.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
      - zipp==3.20.2
      - zope-event==5.0
      - zope-interface==7.2
prefix: /home/shunsuke_ieda@pip.waseda.ac.jp/.conda/envs/INA-DBNet_py38
